#!/bin/sh

if [ "$(lua -v)" == "" ]; then
	echo "install lua5.3, luarocks, curl, unzip and retry."
	exit -1
fi

gh_get() {
	pk=$1
	curl --retry 2 --retry-all-errors -kSL https://github.com/bucketsize/$pk/archive/refs/heads/main.zip -o $pk.zip

	rm $pk-main* -rf
	mv $pk $pk.$(date | md5sum | tr -d " -")

	unzip $pk.zip
	mv $pk-main $pk
}

[ -d ~/.bucketsize ] || mkdir -p ~/.bucketsize
cd ~/.bucketsize

echo "running in [$(pwd)]"

gh_get scripts
export PATH=$HOME/.bucketsize/scripts:$PATH

gh_get minilib
cd minilib; luarocks make --local; cd ..	

gh_get conf-m
cd conf-m; ./setup; cd ..
