[terminal]
vt = 7

[default_session]
# command = "/usr/sbin/agreety --cmd /bin/sh"
# command = "cage -s -- gtkgreet"
command = "/usr/sbin/agreety --cmd xorg-openbox"
# command = "cage -s -- regreet"
# command = "sway --config /etc/greetd/sway-config"

user = "greeter"

[initial_session]
user = "jb"
command = "xorg-openbox"
